Nevest
cristinaboris/newProject pull request #2
Opened 2023-12-01 07:50 UTC by cristinaboris

2023-12-01 10:50 UTC, Nasta7ya requested changes

2023-12-01 10:50 UTC, Nasta7ya commented on src/components/Home/index.jsx
> +      ((event.key === 'Tab' && !event.shiftKey) || event.key === 'Escape')
delete this piece

2023-12-01 10:50 UTC, Nasta7ya commented on src/components/Home/index.jsx
> +  const menuItems = [{name:'Home', ref:'/'}, {name: 'Last Minute Deals', ref:'/deals'}, {name:'Category', ref:'/category'}, {name:'Contacts', ref:'/contct'}];
add formating

2023-12-01 10:50 UTC, Nasta7ya commented on src/components/Home/index.jsx
> +const Linking = styled(Link)(({theme}) => ({
separete this part in file

2023-12-01 10:50 UTC, Nasta7ya commented on src/components/SpecialSection/SpecialSectionTwo.jsx
> + const toTop = () => {
remove

2023-12-01 10:50 UTC, Nasta7ya commented on src/components/SpecialSection/SpecialSectionTwo.jsx
> +//<Container>
comment to remove

2023-12-01 10:50 UTC, Nasta7ya commented on src/redux/reducer.js
> +            items: state.items.slice().sort((a,b)=> b.price - a.price)
decide where it should be

2023-12-01 11:02 UTC, Nasta7ya commented
+ add logic with filterItem

2023-12-15 08:53 UTC, cristinaboris commented on src/components/Home/index.jsx
> +      ((event.key === 'Tab' && !event.shiftKey) || event.key === 'Escape')
done

2023-12-15 09:00 UTC, cristinaboris commented on src/components/Home/index.jsx
> +  const menuItems = [{name:'Home', ref:'/'}, {name: 'Last Minute Deals', ref:'/deals'}, {name:'Category', ref:'/category'}, {name:'Contacts', ref:'/contct'}];
done

2023-12-15 09:01 UTC, cristinaboris commented on src/components/SpecialSection/SpecialSectionTwo.jsx
> + const toTop = () => {
done

2023-12-15 09:02 UTC, cristinaboris commented on src/components/SpecialSection/SpecialSectionTwo.jsx
> +//<Container>
done

2023-12-15 09:02 UTC, cristinaboris commented on src/redux/reducer.js
> +            items: state.items.slice().sort((a,b)=> b.price - a.price)
+

2023-12-15 09:24 UTC, merged